name: {{cookiecutter.project_slug}}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - nb_conda
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
    - -r file:requirements.txt
