name: {{cookiecutter.project_slug}}
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  # - pip:
  #   - git+https://github.com/blaze/dask.git#egg=dask[complete]