# pre-commit
#     - Use pre-commit to automate checks for each commit, see their [website](https://pre-commit.com/) for more info.
#     - Configuration is in */.pre-commit-config.yaml*.
#     - For installation:
#         1. run ```pip install pre-commit``` (or ```pip install env\requirements.txt```) in your environment.
#         2. run ```pre-commit install``` in this repo.
#         3. Now with each commit, pre-commit is automatically executed.
exclude: ''
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-merge-conflict
    - id: no-commit-to-branch
      args: [--branch, master]
    - id: flake8
      additional_dependencies: [flake8-docstrings, pep8-naming]


