# pre-commit
exclude: ''
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-merge-conflict
    - id: no-commit-to-branch
      args: [--branch, master]
    - id: check-json
    - id: check-yaml


