name: Vantage Template

on: [push, pull_request]

jobs:
  build:
    name: Building project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Create instance of our own cookiecutter
      run: |
        pip install cookiecutter
        cookiecutter . --no-input
    - name: Make environment
      run: |
        cd vantage_template_repo
        conda env create -f environment.yaml
        conda activate vantage_template_repo
    - name: Install packages
      run: |
        pip install -e .
    - name: Display packages
      run: |
        pip freeze
    - name: Run tests
      run: |
        pytest tests
